#!/bin/bash

while sleep 2; do
    ADDRESS=`dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf getnewaddress shop`
    [[ ! -z $ADDRESS ]] && break;
    echo "* No address generated ($ADDRESS), continue waiting"
done

echo "* Generating coins..."
sleep 2

dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf generate 101 > /dev/null
dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf generate 101 > /dev/null


dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf sendtoaddress "$ADDRESS" 10000000

echo "sent generated coins to $ADDRESS"

ADDRESS=`dogecoin-cli -conf=/etc/conf/node-2/dogecoin.conf getnewaddress customer`
dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf sendtoaddress "$ADDRESS" 80000000

echo "sent generated coins to $ADDRESS"


echo "* Generating another coins..."
dogecoin-cli -conf=/etc/conf/node-1/dogecoin.conf generate 101  > /dev/null
echo "* Done!"

sleep 2

s6-svc -d /var/run/s6/services/generate